"""empty message

Revision ID: 06178a9a326c
Revises: 8e20b5bb3d65
Create Date: 2019-11-07 16:06:56.790701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06178a9a326c'
down_revision = '8e20b5bb3d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('name', table_name='departments')
    op.drop_table('departments')
    op.add_column('students', sa.Column('university_id', sa.Integer(), nullable=True))
    op.drop_constraint('students_ibfk_1', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'universities', ['university_id'], ['id'])
    op.drop_column('students', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_ibfk_1', 'students', 'departments', ['department_id'], ['id'])
    op.drop_column('students', 'university_id')
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'departments', ['name'], unique=True)
    op.drop_table('universities')
    # ### end Alembic commands ###
