"""empty message

Revision ID: 09ef5d1e3cb2
Revises: 74c4e5864394
Create Date: 2019-11-17 14:15:00.768923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ef5d1e3cb2'
down_revision = '74c4e5864394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('events', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('eventtype_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'universities', ['university_id'], ['id'])
    op.create_foreign_key(None, 'events', 'eventtype', ['eventtype_id'], ['id'])
    op.create_foreign_key(None, 'events', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'university_id')
    op.drop_column('events', 'eventtype_id')
    op.drop_column('events', 'comment_id')
    op.drop_table('rso')
    op.drop_table('eventtype')
    op.drop_table('comments')
    # ### end Alembic commands ###
