"""empty message

Revision ID: 74c4e5864394
Revises: 668e133e201a
Create Date: 2019-11-07 17:55:29.779402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c4e5864394'
down_revision = '668e133e201a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('location', sa.String(length=40), nullable=True))
    op.add_column('events', sa.Column('time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'time')
    op.drop_column('events', 'location')
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
