"""empty message

Revision ID: 8e20b5bb3d65
Revises: 323bd2cc1087
Create Date: 2019-11-07 15:59:52.297707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e20b5bb3d65'
down_revision = '323bd2cc1087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'event_id')
    # ### end Alembic commands ###
