"""empty message

Revision ID: bf18f0eb4aeb
Revises: 09ef5d1e3cb2
Create Date: 2019-11-18 19:11:45.586556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf18f0eb4aeb'
down_revision = '09ef5d1e3cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
